-- Database: mariadb

-- DROP DATABASE mariadb;

-- BEGIN APPLICATION AUTHENTICATION
-- CREATE SEQUENCE FOT TABLE MC_TYPE_OAUTH
/*
CREATE A PROJECT AUTHENTICATION FOR ANY APPLICATION
TECHNOLOGIES:
-JAVA
-POSTGRESQL
-SQL SERVER (REPLICA)
-ANDROID
-SPRING JPA
*/
CREATE SEQUENCE SEQ_MC_TYPE_OAUTH START 1;
-- CREATE TABLE TYPE_OAUTH
CREATE TABLE IF NOT EXISTS MC_TYPE_OAUTH
(
    MC_TYPE_OAUTH_ID INTEGER PRIMARY KEY PK_MC_TYPE_OAUTH NEXTVAL('SEQ_MC_TYPE_OAUTH'), 
    MC_TYPE_OAUTH_DESCRIPTION VARCHAR(100) NOT NULL,
    MC_TYPE_OAUTH_STATUS CHAR(1) NOT NULL,
    MC_TYPE_OAUTH_ALTER_USER VARCHAR(100) NULL,
    MC_TYPE_OAUTH_ALTER_DATE VARCHAR(100) NULL,
    MC_TYPE_OAUTH_ALTER_NETWORK VARCHAR(100) NULL        
)

-- CREATE SEQUENCE FOR TABLE MC_USERS
CREATE SEQUENCE SEQ_MC_USERS START 1;

-- CREATE TABLE MC_USERS
CREATE IF NOT EXISTS TABLE MC_USERS
(
    MC_USERS_ID INTEGER PRIMARY KEY PK_MC_USERS NEXTVAL ('SEQ_MC_USERS'),
    MC_USERS_NAME VARCHAR(100) NOT NULL,
    MC_USERS_DESCRIPTION VARCHAR(200) NULL,
    MC_USERS_AGE INTEGER(3) NULL,
    MC_USERS_GENDER CHAR(1) NULL,
    MC_USERS_LOGIN VARCHAR(100) NOT NULL,
    MC_USERS_PASS VARCHAR(100) NOT NULL,
    MC_USERS_TYPE INTEGER NOT NULL FOREIGN KEY FK_MC_USERS_MC_TYPE_OAUTH REFERENCES MC_TYPE_OAUTH(MC_TYPE_OAUTH_ID),
    MC_USERS_ALTER_USER VARCHAR(100) NULL,
    MC_USERS_ALTER_DATE VARCHAR(100) NULL,
    MC_USERS_ALTER_NETWORK VARCHAR(100)
)


-- CREATE SEQUENCE MC_SESSION_OAUTH
CREATE SEQUENCE SEQ_MC_SESSION_OAUTH START 1;

-- CREATE TABLE MC_SESSION_OAUTH
CREATE IF NOT EXISTS TABLE MC_SESSION_OAUTH
(
    MC_SESSION_OAUTH_ID INTEGER PRIMARY KEY FK_MC_SESSION_OAUTH NEXTVAL('SEQ_MC_SESSION_OAUTH'),
    MC_SESSION_OAUTH_USERS_ID INTEGER NOT NULL FOREIGN KEY FK_SESSION_OAUTH_USERS REFERENCES MC_USERS(MC_USERS_ID),
    MC_SESSION_OAUTH_USER_LOGIN VARCHAR(100) NULL,
    MC_SESSION_OAUTH_BEGIN VARCHAR(20) NULL,
    MC_SESSION_OAUTH_END VARCHAR(20) NULL
)